Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 16

Lint/UselessAssignment:
  Enabled: false

Metrics/LineLength:
  Max: 85

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1

Security/Open:
  Enabled: false
